#!/usr/bin/env python3
"""Generate a Markdown index of Python files, classes, functions, and imports."""

from __future__ import annotations

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "generated" / "py_file_index.md"

INCLUDE_DIRS = [
    "app",
    "core",
    "data_layer",
    "knowledge_layer",
    "reasoning",
    "cognitive_agents",
    "timing_engine",
    "signal_lab",
    "memory_learning",
    "reporting",
    "storage",
    "ingestion",
    "cron_jobs",
    "scripts",
]


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def first_line(text: str) -> str:
    return text.strip().splitlines()[0] if text.strip() else ""


def summarize_file(path: Path) -> str:
    source = path.read_text(encoding="utf-8", errors="ignore")

    try:
        tree = ast.parse(source)
    except SyntaxError:
        return f"## `{rel(path)}`\n\nParse error.\n\n"

    module_doc = ast.get_docstring(tree) or ""

    classes: list[tuple[str, str, list[str]]] = []
    functions: list[tuple[str, str]] = []
    imports: list[str] = []

    for node in tree.body:
        if isinstance(node, ast.Import):
            imports.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                imports.append(node.module)
        elif isinstance(node, ast.ClassDef):
            methods = [
                item.name
                for item in node.body
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))
            ]
            classes.append((node.name, ast.get_docstring(node) or "", methods))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            functions.append((node.name, ast.get_docstring(node) or ""))

    lines: list[str] = []
    lines.append(f"## `{rel(path)}`\n")

    if module_doc:
        lines.append("Module docstring:")
        lines.append(f"> {first_line(module_doc)}")
        lines.append("")

    if imports:
        unique_imports = sorted(set(item for item in imports if item))
        lines.append("Imports:")
        for item in unique_imports[:30]:
            lines.append(f"- `{item}`")
        if len(unique_imports) > 30:
            lines.append(f"- ... {len(unique_imports) - 30} more")
        lines.append("")

    if classes:
        lines.append("Classes:")
        for name, doc, methods in classes:
            lines.append(f"- `{name}`")
            if doc:
                lines.append(f"  - {first_line(doc)}")
            if methods:
                lines.append(f"  - methods: {', '.join(methods)}")
        lines.append("")

    if functions:
        lines.append("Functions:")
        for name, doc in functions:
            lines.append(f"- `{name}`")
            if doc:
                lines.append(f"  - {first_line(doc)}")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    files: list[Path] = []
    for directory in INCLUDE_DIRS:
        base = ROOT / directory
        if base.exists():
            files.extend(sorted(base.rglob("*.py")))

    content = [
        "# Generated Python File Index",
        "",
        "This file is generated by `scripts/generate_py_file_index.py`.",
        "Do not manually edit this file.",
        "",
    ]

    for path in files:
        if "__pycache__" in path.parts:
            continue
        content.append(summarize_file(path))

    OUTPUT.write_text("\n".join(content), encoding="utf-8")
    print(f"Generated {rel(OUTPUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())