import { escapeHTML as e } from '../markdown.mjs';
import { hairlineLine, matrixArc, pairedRungs, rungWaterfall, tickRows } from './charts/lieflat.mjs';
import { anchorRail, blockSources as sources, chapterHeading as sectionHeading, evidenceList, frameworkBot as renderBot, frameworkPanel as panel, sourceNames } from './common.mjs';

export function renderGoldar({ framework, snapshot }, { anchor = 'overview', bot = {} } = {}) {
  const state = snapshot.research_state;
  const fixture = [snapshot.market_context, snapshot.pricing_drivers, snapshot.supply_demand].some((item) => item.status === 'fixture');
  const nav = anchorRail(framework, 'gold', anchor, '黄金研究画布');
  const sourceName = (block) => sourceNames(block, '固定样例');
  return `<article class="framework-detail" data-framework="gold" data-framework-revision="${e(snapshot.revision)}">
    <header class="framework-hero"><div class="framework-hero-main"><a class="framework-back" href="#/frameworks">← 研究框架</a><div class="framework-title-line"><span class="framework-symbol" aria-hidden="true">Au</span><div><span class="eyebrow">COMMODITY FRAMEWORK · V${e(framework.version)}</span><h1>${e(framework.name)}</h1></div></div><p class="framework-question">${e(framework.question)}</p><div class="framework-chain" aria-label="研究链路">${framework.chain.map((item, index) => `<span>${index ? '<i aria-hidden="true">→</i>' : ''}${e(item)}</span>`).join('')}</div></div><aside class="framework-hero-meta"><span class="badge">${fixture ? '固定样例' : '数据快照'}</span><strong>${e(snapshot.status)}</strong><dl><div><dt>观测</dt><dd class="mono">${e(snapshot.as_of)}</dd></div><div><dt>证据</dt><dd class="mono">${snapshot.evidence.length}</dd></div><div><dt>覆盖</dt><dd class="mono">${snapshot.coverage}%</dd></div></dl></aside></header>
    ${fixture ? '<div class="framework-fixture-notice" role="status"><strong>离线确定性样例</strong><span>当前数值用于验证研究结构与图表语言，不代表实时市场；深度验证会明确区分新增证据。</span></div>' : ''}
    <div class="framework-canvas-layout">${nav}<section class="framework-canvas" aria-label="黄金研究画布">
      <section class="framework-chapter" id="framework-overview" aria-labelledby="framework-overview-title">${sectionHeading('overview', 1, '总览', '先看判断、反证和下一项验证，再进入证据链。')}<div class="framework-summary-band"><div><span>当前研究状态</span><strong>${e(state.label)}</strong><small>置信度 <b class="mono">${state.confidence}%</b> · 确定性得分 <b class="mono">${state.score.toFixed(2)}</b></small></div><dl><div><dt>主要支撑</dt><dd>${state.supports.map((item) => `<span>${e(item)}</span>`).join('')}</dd></div><div><dt>主要拖累</dt><dd>${state.drags.map((item) => `<span>${e(item)}</span>`).join('')}</dd></div></dl><aside><span>下一项验证</span><strong>${e(state.next_check)}</strong><button type="button" data-framework-gap="${e(snapshot.gaps[0]?.id || '')}">带着缺口提问 →</button></aside></div><div class="framework-overview-row">${panel('价格只作背景', '完整行情终端仍在资产观察', `<div class="framework-price-line"><strong class="mono">${snapshot.market_context.price.toLocaleString('en-US', { minimumFractionDigits: 1 })}</strong><span class="${snapshot.market_context.change_percent >= 0 ? 'positive' : 'negative'} mono">${snapshot.market_context.change_percent >= 0 ? '+' : ''}${snapshot.market_context.change_percent.toFixed(1)}%</span><small>${snapshot.market_context.range_low}–${snapshot.market_context.range_high}</small></div>${hairlineLine(snapshot.market_context.series, sourceName(snapshot.market_context))}${sources(snapshot.market_context)}`)}${panel('证据覆盖', '缺失、过期或口径冲突阻止确定状态', `<div class="framework-coverage"><div class="framework-coverage-number"><strong class="mono">${snapshot.coverage}%</strong><span>当前覆盖</span></div><div class="framework-coverage-track" aria-label="数据覆盖率 ${snapshot.coverage}%"><i style="--coverage:${snapshot.coverage}%"></i></div><ul>${snapshot.gaps.map((item) => `<li><strong>${e(item.label)}</strong><span>${e(item.next_check)}</span></li>`).join('')}</ul></div>`)}</div></section>
      <section class="framework-chapter" id="framework-drivers" aria-labelledby="framework-drivers-title">${sectionHeading('drivers', 2, '定价驱动', '把宏观关系压缩成可复核的贡献，而不是堆叠指标。')}<div class="framework-two-column">${panel('哪组力量正在定价', 'F9 Rung Waterfall · 一图一结论', rungWaterfall(snapshot.pricing_drivers.factors, sourceName(snapshot.pricing_drivers)))}${panel('读数与解释', '水平、方向和含义保持分列', `<div class="framework-fact-table" role="table">${snapshot.pricing_drivers.relationships.map((item) => `<div class="framework-fact-row" role="row"><strong>${e(item.label)}</strong><span class="mono">${e(item.value)}</span><span>${e(item.direction)}</span><span>${e(item.interpretation)}</span></div>`).join('')}</div>${sources(snapshot.pricing_drivers)}`)}</div><div class="framework-counterline"><span>关键反证</span><strong>${e(framework.counter_evidence[0])}</strong></div></section>
      <section class="framework-chapter" id="framework-supply" aria-labelledby="framework-supply-title">${sectionHeading('supply', 3, '供需与资金', '检查实物需求与资金流是否确认宏观定价。')}<div class="framework-two-column">${panel('需求结构发生了什么变化', 'F6 Paired Rungs · 本期对同期', pairedRungs(snapshot.supply_demand.categories, sourceName(snapshot.supply_demand), { conclusion: '投资与央行需求抵消珠宝需求回落', legend: '淡档 = 同期 · 实档 = 本期 · 数值单位为吨' }))}${panel('资金确认', 'ETF、央行与基差只保留必要读数', `<div class="framework-kpi-list">${snapshot.supply_demand.flows.map((item) => `<article><span>${e(item.label)}</span><strong class="mono">${e(item.value)}</strong><small>${e(item.note)}</small></article>`).join('')}</div>${sources(snapshot.supply_demand)}`)}</div></section>
      <section class="framework-chapter" id="framework-cycle" aria-labelledby="framework-cycle-title">${sectionHeading('cycle', 4, '周期与宏观', '用制度阶段解释因子为什么可能延续或失效。')}<div class="framework-cycle-strip"><div><span>当前政策阶段</span><strong>${e(snapshot.cycle_macro.policy_phase)}</strong></div>${snapshot.cycle_macro.regimes.map((item) => `<article><span>${e(item.label)}</span><strong>${e(item.fit)}</strong><p>${e(item.reason)}</p></article>`).join('')}</div>${sources(snapshot.cycle_macro)}</section>
      <section class="framework-chapter" id="framework-positioning" aria-labelledby="framework-positioning-title">${sectionHeading('positioning', 5, '持仓与期权', '把趋势确认、拥挤与保护需求作为反证检查。')}<div class="framework-two-column">${panel('拥挤与波动', '持仓不直接等于方向预测', `<div class="framework-kpi-list compact">${snapshot.options.positioning.map((item) => `<article><span>${e(item.label)}</span><strong class="mono">${e(item.value)}</strong><small>${e(item.note)}</small></article>`).join('')}</div><div class="framework-proxy-note"><strong>代理指标</strong><span>场外期权不可见，GLD 结构只用于观察压力分布。</span></div>${sources(snapshot.options)}`)}${panel('压力集中在哪里', 'F5 Tick Rows · 上市期权代理', tickRows(snapshot.options.strikes, sourceName(snapshot.options)))}</div></section>
      <section class="framework-chapter" id="framework-allocation" aria-labelledby="framework-allocation-title">${sectionHeading('allocation', 6, '情景与配置', '只说明历史分散化和情景差异，不给出个人仓位。')}<div class="framework-allocation-notes"><article><span>分散化</span><p>${e(snapshot.allocation_context.diversification_note)}</p></article><article><span>回撤</span><p>${e(snapshot.allocation_context.drawdown_note)}</p></article></div><div class="framework-two-column framework-chart-row">${panel('相关性不是常数', 'L4 Arc Matrix · 历史关系', matrixArc(snapshot.allocation_context.correlations, sourceName(snapshot.allocation_context), { title: '跨资产相关性', conclusion: '黄金与美元的负相关最显著' }))}${panel('情景差异', '历史关系不等于未来仓位建议', `<div class="framework-scenario-table"><div class="framework-scenario-head"><span>情景</span><span>黄金</span><span>美股</span><span>美债</span></div>${snapshot.allocation_context.scenarios.map((item) => `<article><strong>${e(item.label)}</strong><span class="mono">${e(item.gold)}</span><span class="mono">${e(item.equities)}</span><span class="mono">${e(item.bonds)}</span><p>${e(item.note)}</p></article>`).join('')}</div>${sources(snapshot.allocation_context)}`)}</div></section>
      <section class="framework-chapter" id="framework-evidence" aria-labelledby="framework-evidence-title">${sectionHeading('evidence', 7, '事件与证据', '证据台账和待验证事件收束整条研究链。')}<div class="framework-two-column">${panel('证据台账', '每条观察保留日期、用途和来源', evidenceList(snapshot.evidence))}${panel('事件雷达', '事件是待验证节点，不预设方向', `<ol class="framework-timeline">${snapshot.events.map((item) => `<li><time class="mono">${e(item.date)}</time><div><span>${e(item.type)}</span><strong>${e(item.title)}</strong><p>${e(item.impact)}</p></div><em>${e(item.status)}</em></li>`).join('')}</ol>`)}</div><details class="framework-method-details"><summary>方法、来源版本与后续扩展</summary><p>${e(framework.method)}</p><p>框架版本 <span class="mono">${e(framework.version)}</span> · 功能参考 <a href="https://github.com/yuxudong-morefun/goldar/tree/${e(framework.source_revision)}" target="_blank" rel="noreferrer">${e(framework.source_revision)}</a>。后续框架通过独立定义、严格快照、采集器与 renderer 注册；Dollar 与首个行业框架落地后再提取真实重复项。</p></details></section>
    </section>${renderBot(bot, snapshot.revision)}</div>
  </article>`;
}
