import { escapeHTML as e } from './markdown.mjs';
import { sessionHash, isRunning } from './core.mjs';
import { modelOptions, renderActivities, renderDatasets, renderDelivery, renderFiles } from './views.mjs';

const navItems = [['fingpt', '⌕', 'FinGPT', '即时研究'], ['claw', '◇', 'Claw', '目标与交付'], ['skills', '▧', '能力中心', '真实 Skills'], ['history', '◷', '历史', '']];

export function filterGlobalSearch(query, sessions = [], skills = []) {
  const normalized = String(query || '').trim().toLocaleLowerCase();
  if (!normalized) return [];
  const work = (Array.isArray(sessions) ? sessions : []).filter((session) => `${session?.title || ''} ${session?.mode || ''}`.toLocaleLowerCase().includes(normalized)).map((session) => ({ kind: 'session', item: session }));
  const capabilities = (Array.isArray(skills) ? skills : []).filter((skill) => `${skill?.name || ''} ${skill?.description || ''}`.toLocaleLowerCase().includes(normalized)).map((skill) => ({ kind: 'skill', item: skill }));
  return [...work, ...capabilities].slice(0, 8);
}

export function renderGlobalSearch(query, sessions, skills) {
  const results = filterGlobalSearch(query, sessions, skills);
  return `<div class="global-search"><label class="sr-only" for="global-search">搜索会话标题和能力名称或简介</label><span aria-hidden="true">⌕</span><input id="global-search" data-global-search type="search" value="${e(query || '')}" placeholder="搜索会话标题、能力名称或简介…" autocomplete="off">${query ? `<div class="global-results" role="listbox">${results.length ? results.map(({ kind, item }) => kind === 'session' ? `<a role="option" href="${sessionHash(item)}" data-global-result="session" data-session-id="${e(item.id)}"><strong>${e(item.title || '未命名会话')}</strong><span>会话 · ${e(item.mode || 'FinGPT')}</span></a>` : `<button type="button" role="option" data-global-result="skill" data-skill-shortcut="${e(item.id)}"><strong>${e(item.name)}</strong><span>${e(item.description || '此 Skill 未提供描述。')}</span></button>`).join('') : '<p class="muted small">没有匹配的真实会话或 Skill。</p>'}</div>` : ''}</div>`;
}

export function renderSidebar({ page, sessionId, sessions = [], workspaces = [], selectedWorkspace = '', collapsed = false, mobileOpen = false } = {}) {
  const recent = Array.isArray(sessions) ? sessions.slice(0, 10) : [];
  const running = recent.filter((session) => isRunning(session.status));
  return `<aside class="sidebar ${mobileOpen ? 'mobile-open' : ''} ${collapsed ? 'collapsed' : ''}" aria-label="研究导航"><div class="sidebar-top"><span class="eyebrow">RESEARCH WORKSPACE</span><button class="icon-button sidebar-close" data-toggle-sidebar aria-label="关闭导航">×</button><button class="icon-button sidebar-collapse" data-collapse-sidebar aria-label="${collapsed ? '展开导航' : '折叠导航'}" aria-expanded="${!collapsed}">${collapsed ? '›' : '‹'}</button></div><div class="sidebar-expanded"><label class="sr-only" for="workspace-select">工作空间</label><select id="workspace-select"><option value="">默认工作空间</option>${workspaces.map((workspace) => `<option value="${e(workspace.id)}" ${selectedWorkspace === workspace.id ? 'selected' : ''}>${e(workspace.name)}</option>`).join('')}</select><button class="button new-session" data-new>＋ 新建研究</button></div><nav class="main-nav" aria-label="产品导航">${navItems.map(([target, icon, title, description]) => `<a href="#/${target}" class="nav-link ${page === target ? 'active' : ''}" ${page === target ? 'aria-current="page"' : ''} title="${e(title)}"><span class="nav-icon" aria-hidden="true">${icon}</span><span class="nav-copy"><strong>${title}</strong>${description ? `<small>${description}</small>` : ''}</span></a>`).join('')}</nav><div class="sidebar-expanded recent-section"><div class="recent-heading"><span class="eyebrow">运行任务</span><span class="count">${running.length}</span></div>${running.length ? running.map((session) => `<a href="${sessionHash(session)}" class="recent-item"><span class="tiny-dot active"></span><span>${e(session.title || '未命名会话')}</span></a>`).join('') : '<p class="muted small sidebar-empty">当前没有运行任务。</p>'}<div class="recent-heading"><span class="eyebrow">最近会话</span><a href="#/history" aria-label="查看全部历史">↗</a></div><div class="recent-sessions">${recent.length ? recent.map((session) => `<a href="${sessionHash(session)}" class="recent-item ${sessionId === session.id ? 'active' : ''}" title="${e(session.title)}"><span class="tiny-dot ${isRunning(session.status) ? 'active' : ''}"></span><span>${e(session.title || '未命名会话')}</span></a>`).join('') : '<p class="muted small sidebar-empty">开始第一项研究后，会话将显示在这里。</p>'}</div></div><div class="sidebar-footer"><a class="nav-link ${page === 'settings' ? 'active' : ''}" href="#/settings" title="设置"><span class="nav-icon" aria-hidden="true">⚙</span><span class="nav-copy"><strong>设置</strong></span></a><span class="local-caption sidebar-expanded">AlphaFoundry Research · DSH</span></div></aside>`;
}

export function renderContextPanel({ detail, selectedTab = 'activity', mobileOpen = false, selectedPreview = null, busy = false } = {}) {
  const tabs = [['activity', '活动'], ['datasets', '资料'], ['files', '文件']];
  const panel = selectedTab === 'datasets' ? renderDatasets(detail?.id, detail?.datasets) || '<p class="muted small context-empty">本会话暂无研究资料。</p>' : selectedTab === 'files' ? `<section class="context-section"><div class="section-heading"><h3>文件</h3>${detail ? `<button class="text-button" data-refresh-files ${busy ? 'disabled' : ''}>刷新</button>` : ''}</div>${renderFiles(detail?.files || [], selectedPreview)}</section>` : `${renderDelivery(detail?.delivery)}${renderActivities(detail)}`;
  return `<aside class="context-panel ${mobileOpen ? 'mobile-open' : ''}" aria-label="研究活动、资料与文件"><header class="context-header"><div><h2>研究空间</h2><span class="badge">${detail?.mode === 'claw' ? 'CLAW' : 'FINGPT'}</span></div><button class="icon-button context-close" data-toggle-context aria-label="关闭研究空间">×</button></header><div class="context-tabs" role="tablist">${tabs.map(([id, label]) => `<button type="button" role="tab" class="context-tab ${selectedTab === id ? 'active' : ''}" aria-selected="${selectedTab === id}" data-context-tab="${id}">${label}</button>`).join('')}</div><div class="context-tab-panel">${panel}</div></aside>`;
}

export function renderTopbar({ runtimeLabel, runtime, models = [], busy = false, search = '', sessions = [], skills = [] } = {}) {
  return `<header class="topbar"><button class="icon-button menu-toggle" data-toggle-sidebar aria-label="打开导航">☰</button><a class="brand" href="#/fingpt"><img src="/static/assets/alphafoundry-logo.png" width="30" height="30" alt=""><span>AlphaFoundry</span><span class="brand-divider"></span><span class="brand-label">Research</span></a>${renderGlobalSearch(search, sessions, skills)}<div class="topbar-right"><a href="#/settings" class="runtime-status"><span class="tiny-dot ${runtime?.connected ? 'active' : ''}"></span>${e(runtimeLabel || 'DSH 未连接')}</a><label class="sr-only" for="model-select">运行模型</label><select id="model-select" ${busy ? 'disabled' : ''}>${modelOptions(models, runtime?.model)}</select><button class="icon-button" data-refresh aria-label="刷新服务状态" title="刷新服务状态">↻</button></div></header>`;
}
